# Generated by Django 6.0.3 on 2026-04-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
