# Generated by Django 6.0.3 on 2026-04-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referralsource",
            name="address",
        ),
        migrations.RemoveField(
            model_name="referralsource",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="referralsource",
            name="email",
        ),
        migrations.RemoveField(
            model_name="referralsource",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="referralsource",
            name="phone",
        ),
        migrations.AddField(
            model_name="referralsource",
            name="tin_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="TIN Number"
            ),
        ),
        migrations.AlterField(
            model_name="referralsource",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Hospital Name"
            ),
        ),
    ]
